# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
    push:
        branches: [master, 'update/**']
    pull_request:
        branches: [master, next]

jobs:
    build:
        name: Build and test for ${{ matrix.os }} - ${{ matrix.node-version }}
        runs-on: ${{ matrix.os }}
        env:
            CI: true
            PLAYWRIGHT_BROWSERS_PATH: 0

        strategy:
            fail-fast: false
            matrix:
                node-version: [18.x, 20.x, 22.x]
                os: [ubuntu-latest, windows-latest, macos-latest]

        steps:
            - uses: actions/checkout@v3

            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v3
              with:
                  cache: 'npm'
                  node-version: ${{ matrix.node-version }}

            - name: Install Dependencies
              run: npm ci --legacy-peer-deps

            - name: Run Tests
              run: npm test
